name: jokes_up
description: A delightful collection of family-friendly jokes to brighten your day.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.0-323.2.beta

dependencies:
  change_app_package_name: ^1.4.0
  curved_navigation_bar: ^1.0.6
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.0
  flutter_staggered_animations: ^1.1.1
  google_fonts: ^6.2.1
  hive: ^2.2.3
  introduction_screen: ^3.1.14
  provider: ^6.1.2
  share_plus: ^10.1.1
  shared_preferences: ^2.3.2
  url_launcher: ^6.3.0
  webview_flutter: ^4.10.0

dev_dependencies:
  icons_launcher: ^3.0.0
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    
icons_launcher:
  image_path: "assets/images/playstore.png"
  platforms:
    android:
      enable: true
      image_path: "assets/images/playstore.png"
      adaptive_background_color: '#FFFFFF'
      adaptive_foreground_image: "assets/images/playstore.png"
