name: jokes_for_all
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.0-323.2.beta

dependencies:
  curved_navigation_bar: ^1.0.6
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.0
  flutter_staggered_animations: ^1.1.1
  google_fonts: ^6.2.1
  hive: ^2.2.3
  introduction_screen: ^3.1.14
  provider: ^6.1.2
  share_plus: ^10.0.2
  shared_preferences: ^2.3.2
  url_launcher: ^6.3.0
  webview_flutter: ^4.9.0

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
